# Generated by Django 4.2.11 on 2026-03-18 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user_type', models.CharField(choices=[('citizen', 'Citizen'), ('volunteer', 'Volunteer')], default='citizen', max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(choices=[('Medical', 'Medical'), ('Security', 'Police/Security'), ('Fire', 'Fire Brigade'), ('General', 'General Help')], default='General', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('location_name', models.CharField(default='Fetching...', max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescuer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
