# Generated by Django 4.2.11 on 2026-03-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='incident',
            name='emergency_type',
            field=models.CharField(choices=[('Medical', 'Medical Emergency'), ('Fire', 'Fire / Short Circuit'), ('Accident', 'Road Accident'), ('Natural Disaster', 'Flood / Landslide'), ('Other', 'Other Problem')], default='Other', max_length=100),
        ),
    ]
